### PR TITLE
[IMP] Multiple improvements

### PR DESCRIPTION
**Pull request by aitorbouzas**
I will be improving step by step some things I consider are not well designed.
Have you considered adding this vertical into OCA?

### CODE REVIEW

**Comment by SythilTech** [comment]
While I agree the fake ticket number could use a revamp and sequences provide new functionality (number padding, etc) I might slate that change for the version 12 port as anyone that updates the module would unexpectedly have there number reset.

I like the timezone translation on the website as that will help to reduce confusion for companies that operate across time zones.

Also could you elaborate what you mean by "Have you considered adding this vertical into OCA?"

**Comment by aitorbouzas** [comment]
Maybe we could make a migration script for the ticket number column. Want me to create one?
With adding this vertical into OCA I mean to add the helpdesk addons into OCA repositories (Odoo Community Association) so the community can upgrade it and maintain it. This is a very nice module (and I thank you very much for your effort, indeed) that is missing in Odoo 11 CE.

**Comment by SythilTech** [comment]
Sure a migration script is fine as long as it can automatically be run when someone upgrades to 1.2.14

If the OCA want to maintain it, I'll happily transfer it to them, I could always use a lighter plate.

**Comment by aitorbouzas** [comment]
@SythilTech fine, the migration script is done, it takes into account the already taken numbers for tickets and updates the sequence to the higher number plus one.
Check also views improvements.

CC @pedrobaeza

**Comment by SythilTech** [comment]
The condensed ticket view is nice, I'll do one last check next time I'm doing some Odoo dev work then give more feedback or otherwise just accept the pull.

I'll also check with OCA if they want to take over the module as it could use a good home now that mostly doing non Odoo stuff nowadays.

**Comment by pedrobaeza** [comment]
@aitorbouzas you pinged me for any special reason?

**Comment by aitorbouzas** [comment]
Yes @pedrobaeza 
I was asking @SythilTech if he's interested in merging this module into OCA. I was just wondering how should we proceed, just making a new PR?

**Comment by pedrobaeza** [comment]
Thanks for clarifying. Well, first of all, this maybe overlaps some things with existing modules (or maybe the core, as there's support now for showing tasks in website portal directly on core module). There's also a proposal for a helpdesk module (on backend). I don't know this one, but a good start can be to put an issue on OCA for explaining the approach and coverage of this module to see what people thinks, and then a PR over OCA signing the CLA.

**Comment by nacho-domatix** [comment]
We could help with the migration to OCA as we are currently working on this module, we already made some improvements for v11 version. Soon a PR will be ready with everything. cc @carlosDomatix
bitmap
(sorry for the spanish language in the screenshots, but the changes can be seen anyway :P)

**Comment by aitorbouzas** [comment]
@dxnacho count on me for reviewing and helping. I've been working with this module with some customers for some time now.

**Comment by nacho-domatix** [comment]
We're working just on v11, but as I said, a PR will be available soon with all the changes so you'll be able to test them (and improve it!). Thank you :)

**Comment by nacho-domatix** [comment]
@aitorbouzas take a look at this: https://github.com/SythilTech/Odoo/pull/50

**Comment by nacho-domatix** [comment]
Hi,
There's gonna be an OCA code sprint next week and we're going to arrange a table with 4-5 developers full time during the whole code sprint just to move this code to OCA repos. 

Is there any chance some people of @SythilTech team can have some time to guide us and supervise all the work? Would be awesome to have a great community contributing to make this "Helpdesk" the community one.

cc @dariolodeiros

**Comment by DarioLodeiros** [comment]
Hi!
@SythilTech , as nacho says, we want to raise a work table to incorporate helpdesk to oca on [Sada CodeSprint](https://www.aeodoo.org/event/dias-espanoles-de-oca-2019-2019-05-27-2019-05-29-26/page/introduccion-dias-espanoles-de-oca-2019).
To be able to base the repository on this module and not lose the authorship of the commits,, we need that all contributors are in agreement with this decision and sign the [CLA of the OCA](https://odoo-community.org/page/cla). 
Since we will be working on this from Monday 27, We need to have your confirmation this week, so we can work on adapting this module to OCA during the codesprint.
Thanks!

**Comment by SythilTech** [comment]
Hi sorry for the late delay seems I missed the 27th, was busy that day anyway as I have a lot of part-time / casual jobs outside of Sythil Tech that keep me busy.

OK, I'm fine with signing the CLA, I'll have to compile a full list of contributors as many people have contributed ideas, bug report and even code via email instead of GitHub and it looks like OCA wants a signature from everyone.

**Comment by aitorbouzas** [comment]
Sorry @SythilTech but we just remade the entire module. We did not take any of your code, we just simply made a simple base module `helpdesk` which will set a foundation over which other contributors can add their own functionalities.
The OCA repository is in https://github.com/OCA/helpdesk and as you will see there's a first PR with the base module.

**Comment by nacho-domatix** [comment]
Hi @SythilTech 

As @aitorbouzas said, developers took already the decision to start it from scratch. It wil be available only from v11 so please consider to contribute to this module in the future instead of continuing your own. There are some advantages in refactoring, and all the features of your module will be developed too. 

We'll be stronger if we unify forces ;) .. and OCA is the best place to be for Odoo code.

**Comment by SythilTech** [comment]
OK, that's cool it does seem like a good idea to start from scratch that way it can be built more modular so it doesn't depend on the website module, there is also a lot of features I've considered redesigning now that the module had grown so much from it's initial concept of a website form to generate support tickets.

I'll see if I can contribute the next time I have a free day or two.

**Comment by aitorbouzas** [comment]
@SythilTech that would be awesome!

As you say, the base module doesn't depend on website and it already has a nice portal view for portal users nicely integrated with Odoo. I hope you can unite your forces with us.

**Pull request merged**
